# Generated by Django 4.0.4 on 2022-07-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_product_picture'),
        ('applicants', '0013_delete_applicantproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('security_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tenure', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('installment_start_date', models.DateField()),
                ('emi', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_product_added_by', to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_products', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Product',
                'verbose_name_plural': 'Applicant Products',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProductChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Pending'), (3, 'Unpaid')])),
                ('challan_number', models.CharField(max_length=999)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='applicants.applicant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.applicantproduct')),
            ],
            options={
                'verbose_name': 'Applicant Produt Challan',
                'verbose_name_plural': 'Applicant Produt Challans',
            },
        ),
        migrations.CreateModel(
            name='FinancingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Financing Mode',
                'verbose_name_plural': 'Financing Modes',
                'db_table': 'Financing Modes',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProductChallanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan_details', to='finance.applicantproductchallan')),
            ],
            options={
                'verbose_name': 'Applicant Product Challan Detail',
                'verbose_name_plural': 'Applicant Product Challan Details',
            },
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='financing_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_products', to='finance.financingmode'),
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
