# Generated by Django 4.0.4 on 2022-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_applicantproductchallan_payable_after_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIChallanBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EMI Challan Bank Account',
                'verbose_name_plural': 'EMI Challan Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='EMIChallanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='challan/logo')),
            ],
            options={
                'verbose_name': 'EMI Challan Profile',
                'verbose_name_plural': 'EMI Challan Profiles',
            },
        ),
    ]
