# Generated by Django 4.0.4 on 2022-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_emichallanbankaccount_emichallanprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emichallanbankaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
