# Generated by Django 4.0.4 on 2022-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_emichallanbankaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproductchallan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Unpaid')], default=1),
        ),
    ]
