# Generated by Django 4.0.4 on 2022-07-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_delete_applicantproduct'),
        ('finance', '0006_alter_applicantproductchallan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantproductchallan',
            options={'verbose_name': 'Applicant Product Challan', 'verbose_name_plural': 'Applicant Product Challans'},
        ),
        migrations.AlterField(
            model_name='applicantproductchallan',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_challans', to='applicants.applicant'),
        ),
    ]
