# Generated by Django 4.0.4 on 2022-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_applicantproductchallan_payable_after_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproductchallan',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
