# Generated by Django 4.0.4 on 2022-06-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MODELNAME',
        ),
        migrations.RenameField(
            model_name='applicantguarantor',
            old_name='mobile',
            new_name='phone',
        ),
    ]
