# Generated by Django 4.0.4 on 2022-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_delete_modelname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='monthly_otherincome',
            new_name='monthly_other_income',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(max_length=150),
        ),
    ]
