# Generated by Django 4.0.4 on 2022-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_rename_monthly_otherincome_applicant_monthly_other_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantguarantor',
            old_name='cnic_photo',
            new_name='cnic_photo_back',
        ),
        migrations.AddField(
            model_name='applicantguarantor',
            name='cnic_photo_front',
            field=models.ImageField(default='default', upload_to='gurantors/cnic'),
            preserve_default=False,
        ),
    ]
