# Generated by Django 4.0.4 on 2022-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_alter_applicant_residing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education_verification',
            field=models.FileField(upload_to='education_verification/'),
        ),
    ]
