# Generated by Django 4.0.4 on 2022-07-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_catgory_product_category'),
        ('settings', '0001_initial'),
        ('applicants', '0006_alter_applicant_education_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantguarantor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_gurantors', to='settings.city'),
        ),
        migrations.CreateModel(
            name='ApplicantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_products', to='applicants.applicant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Applicant Product',
                'verbose_name_plural': 'Applicant Products',
            },
        ),
    ]
