# Generated by Django 4.0.4 on 2022-07-18 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0007_alter_applicantguarantor_city_applicantproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantproduct',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_product_added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='financing_amount',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='rent',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='security_amount',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='tenure',
            field=models.IntegerField(default=132),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantproduct',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
