# Generated by Django 4.0.4 on 2022-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_applicantproduct_installment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproduct',
            name='installment_start_date',
            field=models.DateField(),
        ),
    ]
