# Generated by Django 4.0.4 on 2022-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_applicantproduct_installment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantproduct',
            name='EMI',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
