# Generated by Django 4.0.4 on 2022-07-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_applicantproduct_emi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantproduct',
            old_name='EMI',
            new_name='emi',
        ),
    ]
