# Generated by Django 4.0.4 on 2022-06-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgory',
            new_name='category',
        ),
    ]
